server:
  port: 8071

spring:
  application:
    name: microServiceConsumer
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-single:8761/eureka/
  instance:
    instance-id: microServiceConsumer-instanceid

feign:
  hystrix:
    enabled: true


logging:
  level:
    org.springframework.cloud: debug